package com.example.data.entity

import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "saas_config")
data class SaaSConfigEntity(
    @PrimaryKey val tenantId: String,
    val hospitalName: String,
    val subscriptionPlan: String, // "Freetrial", "Silver", "Gold", "Platinum"
    val subscriptionStatus: String, // "Active", "Suspended"
    val subscriptionExpiry: String,
    val currentDoctorsCount: Int,
    val maxDoctorsCount: Int,
    val currentPatientsCount: Int,
    val totalRevenue: Double
)

@Entity(tableName = "patients")
data class PatientEntity(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    val name: String,
    val age: Int,
    val gender: String, // "ذكر" (Male), "أنثى" (Female)
    val phone: String,
    val address: String,
    val bloodGroup: String, // "A+", "B+", etc.
    val isIPD: Boolean, // true if Inpatient, false if Outpatient (OPD)
    val roomNumber: String?, // Room number if IPD
    val latestComplaints: String,
    val admissionDate: String
)

@Entity(tableName = "doctors")
data class DoctorEntity(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    val name: String,
    val specialty: String, // "باطنية", "أطفال", "قلب", "جراحة", etc.
    val phone: String,
    val email: String,
    val availableDays: String, // e.g. "أحد، ثلاثاء، خميس"
    var status: String // "متاح" (Active), "في عملية" (In Surgery), "خارج المناوبة" (Away)
)

@Entity(tableName = "appointments")
data class AppointmentEntity(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    val patientId: Int,
    val patientName: String,
    val doctorId: Int,
    val doctorName: String,
    val date: String,
    val time: String,
    val status: String, // "قيد الانتظار" (Pending), "مؤكد" (Confirmed), "مكتمل" (Completed), "ملغي" (Cancelled)
    val symptoms: String,
    val diagnosisSummary: String? = null, // Can be generated by Smart AI (Gemini)
    val isSmartSummaryGenerated: Boolean = false
)

@Entity(tableName = "pharmacy_items")
data class PharmacyItemEntity(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    val name: String,
    val category: String, // "مسكنات", "مضادات حيوية", "فيتامينات", etc.
    val quantity: Int, // Stock count
    val price: Double, // Price per unit
    val unit: String // "علبة", "قرص", "شراب", etc.
)

@Entity(tableName = "bills")
data class BillEntity(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    val patientId: Int,
    val patientName: String,
    val amount: Double,
    val date: String,
    val itemsSummary: String, // Description of charges, e.g. "كشفية طبيب + أدوية"
    val status: String // "مدفوع" (Paid), "غير مدفوع" (Unpaid)
)
